BrainCapture:
  name: BrainCapture 
  toplevel: /zhome/15/a/181503/BrainCapture/BENDR/data/standardized_BraiCapture_data/
  tmin: 0
  tlen: 4
  data_max: 0.00125
  data_min: -0.00125
  events: # Annotations
    - "Eye blinking"
    - "Eye movement left-right"
    - "Eyes closed"
    - "Look straight forward keep"
    - "Jaw clenching"
    - "Hyperventilation"
  extensions:
    - .edf
  train_params:
    epochs: 50
    batch_size: 4 # I find this dataset likes small batch sizes
  lr: 0.00001
  folds: 136 # Folds = Subjects