Configuratron:
  use_only:
    - tueg_v2
    - mmidb
  samples: 15360 # = 60 seconds
  sfreq: 256
  deep1010:
    return_mask: True

validation_dataset: mmidb

augmentation_params:
  upsample_crop: 32
  batch_crop_frac: 0.05

training_params:
  epochs: 10
  validation_interval: 100
  train_log_interval: 100
  batch_size: 16
  warmup_frac: 0.05

mask_threshold: 0.85
mask_inflation: 1.
mask_pct_max: 0.6

optimizer_params:
  lr: 0.00002
  weight_decay: 0.01
  betas: [0.9, 0.98]

bending_college_args:
  mask_rate: 0.065
  mask_span: 10
  layer_drop: 0.01
  multi_gpu: True
  temp: 0.1
  encoder_grad_frac: 0.1
  num_negatives: 20
  enc_feat_l2: 1.0

datasets:
  tueg_v2:
    name: "TUH EEG v2.0.0"
    data_max: 0.00125
    data_min: -0.00125
    toplevel: /scratch/s194260/tuh_eeg_quality
    stride: 15360 # = 256 * 60 = 1 min
    dataset_id: 2
    task_id: 2
    preload: False
    rename_channels:
      CP3: "*C3P*"
      CP4: "*C4P*"
      FT9: "*T1*"
      FT10: "*T2*"
    exclude_channels: !include configs/tueg_channel_exclusions.yml
    load_onthefly: True
    picks:
      - eeg

  mmidb:
    name: "Physionet MMIDB"
    toplevel: /scratch/s194260/eegmmidb
    tmin: 0
    tlen: 4
    data_max: 0.00125
    data_min: -0.00125
    events:
      - T1
      - T2
    exclude_sessions:
      - "*R0[!48].edf"  # equivalently "*R0[1235679].edf"
      - "*R1[!2].edf"   # equivalently "*R1[134].edf"
    exclude_people:
      - S088
      - S090
      - S092
      - S100
    train_params:
      epochs: 50
      batch_size: 4 # I find this dataset likes small batch sizes
    lr: 0.00001
    folds: 105
